### ISSUE TITLE
ConvertDocxToPdfExample fails with ClassCastException with using-graph-sdk

### ISSUE THREAD

**Issue by deas** [plutext/java-docx-to-pdf-using-Microsoft-Graph#2]
I get the following exception running the current `ConvertDocxToPdfExample` with `using-graph-sdk`:
```
        java.lang.ClassCastException: java.io.BufferedInputStream cannot be cast to com.microsoft.graph.models.extensions.UploadSession

	at com.microsoft.graph.requests.extensions.DriveItemCreateUploadSessionRequest.post(DriveItemCreateUploadSessionRequest.java:44)
	at org.plutext.msgraph.convert.graphsdk.PdfConverterLarge.convert(PdfConverterLarge.java:105)
```

The demo works fine for me using `using-graph-sdk-core-only` instead.

**Comment by plutext** [comment]
Thanks for this.  The code needs to be updated to use a more recent version of Microsoft's API.

It looks like a fairly straightforward process, but we're currently having difficulties with our Microsoft account, so we're unable to test the updates at the moment.

**Comment by plutext** [comment]
Should work now
